contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #phevir channel"
    url: https://nfcore.slack.com/channels/phevir
    about: Discussion about the nf-core/phevir pipeline
